apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: packit
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: packit
    app.kubernetes.io/part-of: packit
  name: packit
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: packit
status:
  loadBalancer: {}
